In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

%pwd

'C:\\Users\\casti\\OneDrive\\Documents\\A Springboard\\Capstone 2 - Global Terrorism\\notebooks'

In [3]:
file_path = r"C:\Users\casti\OneDrive\Documents\A Springboard\Capstone 2 - Global Terrorism\data\raw\globalterrorismdb_0522dist.xlsx"

gtd = pd.read_excel(file_path)

In [121]:
file_path2 = r"C:\Users\casti\OneDrive\Documents\A Springboard\Capstone 2 - Global Terrorism\data\raw\globalterrorismdb_2021Jan-June_1222dist.xlsx"

gtd2 = pd.read_excel(file_path2)

In [4]:
gtd.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaT,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaT,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaT,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaT,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaT,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [7]:
gtd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 216.0+ MB

In [134]:
gtd2.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,202101010004,2021,1,1,NaN,0,NaT,60,Egypt,10,...,NaN,"""Egyptian officials: Roadside bombing in Sinai...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
1,202101010005,2021,1,1,01/01/2021,0,NaT,92,India,6,...,NaN,"""Terror module busted, seven arrested in J&K,""...","""Militants throw grenade on CRPF,"" HT Syndicat...",NaN,START Primary Collection,-9,-9,0,-9,NaN
2,202101010006,2021,1,1,NaN,0,NaT,228,Yemen,10,...,There is doubt that this incident meets terror...,"""Civilian reportedly dies of injuries from Hou...","""UN troubled by civilian deaths in Yemen's Hud...","""Five women killed in Yemen wedding attack,"" G...",START Primary Collection,0,0,0,0,NaN
3,202101010009,2021,1,1,NaN,0,NaT,4,Afghanistan,6,...,There is doubt that this incident meets terror...,"""Afghanistan- Ghor Provincial Council Member K...","""Journalist killed on 1st day of new year in A...","""Afghanistan: 2021 Begins with Assassination o...",START Primary Collection,-9,-9,0,-9,NaN
4,202101010024,2021,1,2,NaN,0,NaT,182,Somalia,11,...,NaN,"""Jubbaland lawmaker killed in car bomb blast,""...","""Somali lawmaker killed in a sticky bomb attac...","""Al-Shabab claims killing regional MP in south...",START Primary Collection,0,0,0,0,NaN

In [126]:
gtd2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4960 entries, 0 to 4959
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(51), int64(29), object(54)
memory usage: 5.1+ MB

In [129]:
columns1 = list(gtd.columns)
columns2 = list(gtd2.columns)

for x in columns1 :
    if x not in columns2:
        print(f"{x} from GTD1 is not in GTD2.")
for y in columns2 :
    if y not in columns1:
        print(f"{y} from GTD2 is not in GTD1.")

In [130]:
gtdbig = pd.concat([gtd, gtd2], join='outer',ignore_index=True)

In [131]:
gtdbig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214666 entries, 0 to 214665
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 221.1+ MB

In [135]:
gtd2.loc[gtd2['country']==217]

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
23,202101040015,2021,1,4,NaN,0,NaT,217,United States,1,...,There is doubt that this incident meets terror...,"""Man with rifle shot by troopers outside Misso...","""Missouri patrol shoots man who fired at troop...",NaN,START Primary Collection,-9,-9,0,-9,NaN
47,202101060016,2021,1,6,NaN,0,NaT,217,United States,1,...,The victims included police officers from the ...,"""FBI posts new photos of DC pipe bomb suspect ...",NaN,NaN,START Primary Collection,0,0,0,0,"202101060016, 202101060017, 202101060018"
48,202101060017,2021,1,6,NaN,0,NaT,217,United States,1,...,NaN,"""Feds rushing to find leads on person who put ...","""Capitol Bomber Remains At Large: FBI Offers $...","""Pipe Bombs Believed To Have Been Placed Night...",START Primary Collection,-9,-9,0,-9,"202101060016, 202101060017, 202101060018"
49,202101060018,2021,1,6,NaN,0,NaT,217,United States,1,...,NaN,"""Feds rushing to find leads on person who put ...","""Capitol Bomber Remains At Large: FBI Offers $...","""Pipe Bombs Believed To Have Been Placed Night...",START Primary Collection,-9,-9,0,-9,"202101060016, 202101060017, 202101060018"
110,202101140016,2021,1,14,NaN,0,NaT,217,United States,1,...,The victims included Matthew Camp and Six Cart...,"""Hell to pay: Arson shakes a Church of Satan c...","""OnlyFans star Matthew Camp narrowly escapes a...",NaN,START Primary Collection,-9,-9,0,-9,NaN
146,202101180026,2021,1,18,NaN,0,NaT,217,United States,1,...,There is doubt that this incident meets terror...,"""Ohio police officer killed in armed standoff ...","""Ohio cathedral vandalism suspect, police offi...",NaN,START Primary Collection,-9,-9,0,-9,NaN
186,202101230019,2021,1,23,NaN,0,NaT,217,United States,1,...,NaN,"""FBI offers $25,000 reward in El Monte church ...","""Homemade bomb thrown at Los Angeles church co...","""Authorities investigating explosion at Los An...",START Primary Collection,-9,-9,0,-9,NaN
505,202102250015,2021,2,25,NaN,0,NaT,217,United States,1,...,NaN,"""Arson, Hate Crime Investigation After Windows...","""Community and Faith Organizations Concerned O...",NaN,START Primary Collection,-9,-9,0,-9,NaN
550,202103020018,2021,3,2,NaN,0,NaT,217,United States,1,...,There is doubt that this incident meets terror...,"""Pipe bomb found at Iowa polling location for ...","""Police: Live pipe bomb found at polling place...","""A Homemade Bomb was Found Near a Public Cente...",START Primary Collection,-9,-9,0,-9,NaN
574,202103060013,2021,3,6,NaN,0,NaT,217,United States,1,...,NaN,"""Portland Public Schools headquarters vandaliz...","""Portland Public Schools headquarters targeted...","""After Antifa Group Tweets 'Burn the Schools,'...",START Primary Collection,-9,-9,0,-9,NaN
635,202103150031,2021,3,15,NaN,0,NaT,217,United States,1,...,NaN,"""QAnon Supporter Allegedly Fired Paintballs at...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
641,202103160007,2021,3,16,NaN,0,NaT,217,United States,1,...,The victims included Paul Andre Michels and El...,"""What we know about Robert Aaron Long, the sus...","""Atlanta Shootings: What Korean-Language Media...","""What We Know About the Victims in the Atlanta...",START Primary Collection,-9,-9,1,1,"202103160007, 202103160008, 202103160009"
642,202103160008,2021,3,16,NaN,0,NaT,217,United States,1,...,The suspect had previously been a customer at ...,"""What we know about Robert Aaron Long, the sus...","""Atlanta Shootings: What Korean-Language Media...","""U.S. News: Biden Decries Atlanta Attack Durin...",START Primary Collection,-9,-9,1,1,"202103160007, 202103160008, 202103160009"
643,202103160009,2021,3,16,NaN,0,NaT,217,United States,1,...,The suspect had previously been a customer at ...,"""What we know about Robert Aaron Long, the sus...","""Atlanta Shootings: What Korean-Language Media...","""U.S. News: Biden Decries Atlanta Attack Durin...",START Primary Collection,-9,-9,0,-9,"202103160007, 202103160008, 202103160009"
710,202103250040,2021,3,25,NaN,0,NaT,217,United States,1,...,NaN,"""Arson suspected after fire destroys historic ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
753,202104020015,2021,4,2,NaN,0,NaT,217,United States,1,...,There is doubt this incident meets terrorism-r...,"""Capitol Police officer wounded in car-ramming...","""Suspect in attack at U.S. Capitol went from j...","""Who Is Noah Green? Here’s What We Know About ...",START Primary Collection,-9,-9,0,-9,NaN
848,202104150036,2021,4,15,NaN,0,NaT,217,United States,1,...,There is doubt this incident meets terrorism-r...,"""Treating the Indianapolis attack as a hate cr...","""Sikhs, South Asians call for solidarity acros...","""Gunman in Indiana FedEx massacre bought rifle...",START Primary Collection,-9,-9,0,-9,NaN
910,202104240010,2021,4,24,NaN,0,NaT,217,United States,1,...,NaN,"""Terre Haute police investigating after improv...","""Man arrested after IED found outside Terre Ha...","""IED found near Terre Haute Police headquarter...",START Primary Collection,-9,-9,0,-9,NaN
1162,202105190047,2021,5,19,NaN,0,NaT,217,United States,1,...,NaN,"""Man Faces Arson Charges After Attack on Synag...","""Brooklyn man allegedly attempted to torch syn...","""ATF - Brooklyn Man Arrested for Arson of Yesh...",START Primary Collection,-9,-9,0,-9,"202105190047, 202105190048"
1163,202105190048,2021,5,19,NaN,0,NaT,217,United States,1,...,NaN,"""Man Faces Arson Charges After Attack on Synag...","""Brooklyn man allegedly attempted to torch syn...","""ATF - Brooklyn Man Arrested for Arson of Yesh...",START Primary Collection,-9,-9,0,-9,"202105190047, 202105190048"
1168,202105200015,2021,5,20,NaN,0,NaT,217,United States,1,...,NaN,"""Officers take cover after shots fired outside...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
1183,202105220015,2021,5,22,NaN,0,NaT,217,United States,1,...,NaN,"""NYPD sending more cops to Jewish neighborhood...","""Anti-Semitic attacks spark new NYPD patrols,""...","""NYPD searching for suspects after pair of ant...",START Primary Collection,-9,-9,0,-9,NaN
1200,202105230046,2021,5,23,NaN,0,NaT,217,United States,1,...,NaN,"""Maryland man accused of intentionally crashin...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
1206,202105240050,2021,5,24,NaN,0,NaT,217,United States,1,...,NaN,"""'No vaccine!': Woman arrested for allegedly d...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
1422,202106210026,2021,6,21,NaN,0,NaT,217,United States,1,...,The victims included Johnny Hurley.,"""Bystander Who Intervened in Shooting of Offic...","""John Hurley, hailed by police as “true hero,”...",NaN,START Primary Collection,-9,-9,0,-9,NaN
1471,202106260058,2021,6,26,NaN,0,NaT,217,United States,1,...,NaN,"""Gunman who killed two people after crashing s...","""Victims of deadly Winthrop, Massachusetts, sh...","""How a Mass. sergeant singlehandedly stopped a...",START Primary Collection,-9,-9,0,-9,NaN

In [140]:
gtdus = gtdbig.loc[gtdbig['country']==217,:]
print(gtdus.info())
gtdus.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3147 entries, 5 to 211177
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 3.3+ MB
None

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
5,197001010002,1970,1,1,NaN,0,NaT,217,United States,1,...,"The Cairo Chief of Police, William Petersen, r...","""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,-9,-9,0,-9,NaN
7,197001020002,1970,1,2,NaN,0,NaT,217,United States,1,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
8,197001020003,1970,1,2,NaN,0,NaT,217,United States,1,...,The New Years Gang issue a communiqué to a loc...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",Hewitt Project,0,0,0,0,NaN
9,197001030001,1970,1,3,NaN,0,NaT,217,United States,1,...,"Karl Armstrong's girlfriend, Lynn Schultz, dro...",Committee on Government Operations United Stat...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...",Hewitt Project,0,0,0,0,NaN
10,197001050001,1970,1,1,NaN,0,NaT,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN

In [141]:
gtduscity = sorted(list(gtdus.city.unique()))
gtduscity

['Acworth',
 'Afton',
 'Aguada',
 'Aguadilla',
 'Aibonito',
 'Akron',
 'Alameda',
 'Alamogordo',
 'Albany',
 'Albertville',
 'Albion',
 'Albuquerque',
 'Alexandria',
 'Alhambra',
 'Altadena',
 'Alto',
 'Alton',
 'Amarillo',
 'Ames',
 'Amherst',
 'Anaheim',
 'Anamosa',
 'Anderson',
 'Andrews',
 'Ankeny',
 'Ann Arbor',
 'Annapolis',
 'Antioch',
 'Appleton',
 'Aptos',
 'Arcata',
 'Arecibo',
 'Arivaca',
 'Arlington',
 'Arvada',
 'Asbury',
 'Asheville',
 'Ashland',
 'Ashville',
 'Astoria',
 'Athens',
 'Atherton',
 'Atkins',
 'Atlanta',
 'Auburn',
 'Augusta',
 'Aurora',
 'Austin',
 'Axton',
 'Aztec',
 "Bailey's Crossroads",
 'Bakersfield',
 'Baldwin Park',
 'Baltimore',
 'Baraboo',
 'Barnegat',
 'Batavia',
 'Baton Rouge',
 'Baxter Springs',
 'Bayamon',
 'Beaumont',
 'Bedford Park',
 'Bel Air',
 'Bellevue',
 'Bellflower',
 'Bellingham',
 'Belmont',
 'Ben Lomond',
 'Bend',
 'Berkeley',
 'Berlin',
 'Bessemer',
 'Bethesda',
 'Beverly Hills',
 'Biggsville',
 'Billings',
 'Birmingham',
 'Blooming Grove',
 'Bloomington',
 'Bluefield',
 'Boca Raton',
 'Boise',
 'Bonners Ferry',
 'Borinquen',
 'Boston',
 'Boulder',
 'Boulder City',
 'Boynton Beach',
 'Bozeman',
 'Brainerd',
 'Braintree',
 'Brentwood',
 'Brewster',
 'Bridgeport',
 'Bridgeton',
 'Brighton',
 'Bristol',
 'Broken Arrow',
 'Brookline',
 'Brooklyn Center',
 'Brunswick',
 'Buckeystown',
 'Buena Vista County',
 'Buffalo',
 'Bullard',
 'Bunkerville',
 'Burien',
 'Burlingame',
 'Burlington',
 'Burns',
 'Caguas',
 'Cairo',
 'Caldwell',
 'Camano',
 'Cambridge',
 'Camden',
 'Campbelltown',
 'Canton',
 'Cape Girardeau',
 'Capitol Heights',
 'Capitola',
 'Carlisle',
 'Carmichael',
 'Carolina',
 'Carrollton',
 'Carson City',
 'Casa Grande',
 'Cayey',
 'Century',
 'Cerritos',
 'Champaign',
 'Chandler',
 'Chantilly',
 'Chapel Hill',
 'Chappaqua',
 'Charleston',
 'Charlotte',
 'Charlotte Amalie',
 'Charlotte Amalie West',
 'Charlottesville',
 'Chattanooga',
 'Cherry Hill',
 'Chester',
 'Chicago',
 'Chico',
 'Chula Vista',
 'Cicero',
 'Cidra',
 'Cieba',
 'Cincinnati',
 'Claremont',
 'Clatskanie',
 'Cle Elum',
 'Clearwater',
 'Cleveland',
 'Cleveland Heights',
 'Cloverdale',
 'Coachella',
 'Coamo',
 "Coeur D'Alene",
 'College Park',
 'College Station',
 'Colorado Springs',
 'Columbia',
 'Columbus',
 'Compton',
 'Concord',
 'Condado',
 'Coos Bay',
 'Coral Gables',
 'Cordelia',
 'Corinth',
 'Corona',
 'Corpus Christi',
 'Corvallis',
 'Covington',
 'Cullman',
 'Culver City',
 'Cumming',
 'Cupertino',
 'Dallas',
 'Dalton',
 'Danbury',
 'Davenport',
 'Davis',
 'Dayton',
 'Daytona Beach',
 'DeWitt',
 'Decatur',
 'Deer Park',
 'Delaware City',
 'Deming',
 'Denver',
 'Des Moines',
 'Des Plaines',
 'Detroit',
 'Dewitt',
 'Dixon',
 'Dobbs Ferry',
 'Dorado',
 'Doraville',
 'Dover',
 'Draper',
 'Dulles',
 'Duluth',
 'Dundalk',
 'East Lansing',
 'East Los Angeles',
 'East Meadow',
 'East St. Louis',
 'Eastchester',
 'Edgemont',
 'Edison',
 'Edmonds',
 'Edwardsville',
 'El Granada',
 'El Monte',
 'El Paso',
 'El Toro',
 'Eldridge',
 'Elizabeth',
 'Elkmont',
 'Elmont',
 'Ely',
 'Emeryville',
 'Endicott',
 'Erie',
 'Escanaba',
 'Escondido',
 'Essexville',
 'Estacada',
 'Eugene',
 'Eureka',
 'Evanston',
 'Everett',
 'Fairbanks',
 'Fairfield',
 'Fairport',
 'Fairton',
 'Fajardo',
 'Falls Church',
 'Fargo',
 'Farley',
 'Fayetteville',
 'Fitchburg',
 'Flagstaff',
 'Flint',
 'Folcroft',
 'Forest Grove',
 'Forest Lake',
 'Fort Benning',
 'Fort Collins',
 'Fort Davis',
 'Fort Lauderdale',
 'Fort Lupton',
 'Fort Myers',
 'Fort Pierce',
 'Fort Smith',
 'Fort Wayne',
 'Fort Worth',
 'Franklin',
 'Freedom',
 'Freeport',
 'Fremont',
 'Fresno',
 'Fullerton',
 'Fulton',
 'Gadsden',
 'Gainesville',
 'Galesburg',
 'Garden Grove',
 'Garland',
 'Gilroy',
 'Girard',
 'Glen Burnie',
 'Glen Cove',
 'Glendale',
 'Gloucester City',
 'Graceville',
 'Granada Hills',
 'Grand Canyon',
 'Grand Chute',
 'Grand Forks',
 'Grand Rapids',
 'Granite City',
 'Grants Pass',
 'Greeleyville',
 'Green Bay',
 'Green Township',
 'Greenburgh',
 'Greencastle',
 'Greenland',
 'Greensboro',
 'Greenville',
 'Guanica',
 'Guayama',
 'Guaynabo',
 'Hagerstown',
 'Hammond',
 'Hannibal',
 'Hanover',
 'Harrisburg',
 'Harrison',
 'Hartford',
 'Hato Rey',
 'Hattiesburg',
 'Haverhill',
 'Havre de Grace',
 'Hawthorne',
 'Hayden',
 'Hayden Lake',
 'Hayward',
 'Helena',
 'Hemet',
 'Hempstead',
 'Hialeah',
 'Hillsborough',
 'Hoboken',
 'Hollister',
 'Holly Springs',
 'Hollywood',
 'Honolulu',
 'Houghton',
 'Houston',
 'Hudson Bend',
 'Hughson',
 'Humacao',
 'Huntington',
 'Huntington Beach',
 'Hyattsville',
 'Hyder',
 'Independence',
 'Indian Head',
 'Indianapolis',
 'Inglewood',
 'Inwood',
 'Iowa City',
 'Irvine',
 'Isla Vista',
 'Island in the Forks',
 'Ithaca',
 'Jackson',
 'Jacksonville',
 'Jeffersontown',
 'Jennings',
 'Jericho',
 'Jersey City',
 'Johnstown',
 'Joliet',
 'Joplin',
 'Juana Diaz',
 'Kailua',
 'Kalaeloa',
 'Kalamazoo',
 'Kalispell',
 'Kannapolis',
 'Kansas City',
 'Katonah',
 'Katy',
 'Kent',
 'Keyes',
 'Keystone',
 'Killeen',
 'Knoxville',
 'La Jolla',
 'La Quinta',
 'Lacey',
 'Lafayette',
 'Laguna Gardens',
 'Laguna Niguel',
 'Lake Forest',
 'Lake Los Angeles',
 'Lake Worth',
 'Lakedale',
 'Lakeside',
 'Lakewood',
 'Lamoille',
 'Lancaster',
 'Langley Park',
 'Lansdowne',
 'Laramie',
 'Laredo',
 'Las Cruces',
 'Las Vegas',
 'Lathrup Village',
 'Laurel',
 'Lawrence',
 'Lawrenceville',
 'Leavenworth',
 "Lee's Summit",
 'Leeton',
 'Levittown',
 'Lewiston',
 'Lexington',
 'Lilburn',
 'Lincoln',
 'Litchfield',
 'Little Rock',
 'Littleton',
 'Livermore',
 'Livingston',
 'Lockland',
 'Logan',
 'Lombard',
 'Long Beach',
 'Longmeadow',
 'Longview',
 'Los Altos',
 'Los Altos Hills',
 'Los Angeles',
 'Los Gatos',
 'Louisville',
 'Lowell',
 'Lubbock',
 'MIami',
 'Macon',
 'Madison',
 'Manati',
 'Manchester',
 'Mandan',
 'Manhattan Beach',
 'Manning',
 'Maple Grove',
 'Marietta',
 'Marina',
 'Marion',
 'Marlborough',
 'Martinez',
 'Martiny',
 'Maryland Heights',
 'Maryville',
 'Mayaguez',
 'McCook',
 'McLean',
 'Medford',
 'Medina',
 'Melbourne',
 'Melrose',
 'Melville',
 'Memphis',
 'Menlo Park',
 'Merced',
 'Meriden',
 'Merrillville',
 'Mesa',
 'Mesick',
 'Mesquite',
 'Metairie',
 'Metter',
 'Miami',
 'Miami Beach',
 'Middle Island',
 'Middleburg Heights',
 'Mill Valley',
 'Miller Place',
 'Millville',
 'Milpitas',
 'Milwaukee',
 'Mineola',
 'Minneapolis',
 'Missoula',
 'Mobile',
 'Modesto',
 'Monaca',
 'Monmouth',
 'Monroe',
 'Monsey',
 'Montebello',
 'Monterey',
 'Montgomery',
 'Morgan Hill',
 'Morganton',
 'Morrison',
 'Mount Carroll',
 'Mount Gilead',
 'Mount Sinai',
 'Mount Vernon',
 'Mountain Brook',
 'Mountain View',
 'Mt. Lebanon',
 'Murfreesboro',
 'Murphy',
 'Murray',
 'Naguabo',
 'Naranjito',
 'Nashville',
 'Nassau county',
 'National Harbor',
 'Nederland',
 'Needham',
 'Nesconset',
 'Nevada City',
 'New Bedford',
 'New Berlin',
 'New Britain',
 'New Castle',
 'New City',
 'New Haven',
 'New London',
 'New Market',
 'New Orleans',
 'New York',
 'New York City',
 'Newark',
 'Newburyport',
 'Newport Beach',
 'Newport News',
 'Newton',
 'Niwot',
 'Nogales',
 'Nome',
 'Norfolk',
 'Norman',
 'Norris',
 'North Charleston',
 'North Hornell',
 'North Vernon',
 'Northborough',
 'Northbrook',
 'Northridge',
 'Norwalk',
 'Novato',
 'Oak Creek',
 'Oakland',
 'Oakland Park',
 'Oakridge',
 'Oakwood',
 'Ocala',
 'Ogden',
 'Ohiowa',
 'Oklahoma City',
 'Olathe',
 'Olema',
 'Olympia',
 'Omaha',
 'Oneonta',
 'Onondaga',
 'Opa-locka',
 'Opelika',
 'Opelousas',
 'Orange Park',
 'Oregon City',
 'Orland Park',
 'Orlando',
 'Oskaloosa',
 'Overland Park',
 'Oxford',
 'Oxnard',
 'Pacific Beach',
 'Palm Beach Gardens',
 'Palo Alto',
 'Palo Verde',
 'Paramount',
 'Paramus',
 'Parkland',
 'Parma',
 'Pasadena',
 'Paso Robles',
 'Paterson',
 'Pelham Manor',
 'Pendleton',
 'Pensacola',
 'Penuelas',
 'Peoria',
 'Perrysburg',
 'Perryville',
 'Petaluma',
 'Pewaukee',
 'Philadelphia',
 'Phoenix',
 'Pima County Estates',
 'Pine Ridge',
 'Piperton',
 'Pittsburgh',
 'Placentia',
 'Plainfield',
 'Plano',
 'Pleasanton',
 'Plymouth',
 'Pomona',
 'Ponce',
 'Pontiac',
 'Port Barre',
 'Port St. Lucie',
 'Portland',
 'Poughkeepsie',
 'Poway',
 'Prairie du Sac',
 'Princeton',
 'Providence',
 'Provo',
 'Pueblo',
 'Puerto Nuevo',
 'Pullman',
 'Puyallup',
 'Quincy',
 'Racine',
 'Rainier',
 'Rajneeshpurram',
 'Rapid City',
 'Reading',
 'Reasnor',
 'Redding',
 'Redlands',
 'Redmond',
 'Redwood City',
 'Reisterstown',
 'Reno',
 'Renton',
 'Revere',
 'Richfield',
 'Richmond',
 'Richmond Heights',
 'Rio Grande',
 'Rio Piedras',
 'Riverside',
 'Roanoke',
 'Robbinsdale',
 'Rochester',
 'Rock Springs',
 'Rockford',
 'Rockville',
 'Rocky Mount',
 'Rodeo',
 'Rolling Hills Estates',
 'Roseburg',
 'Rossmore',
 'Roswell',
 'Rotterdam',
 'Rutherford',
 'Sabana Seca',
 'Sacramento',
 'Salida',
 'Salinas',
 'Salt Lake City',
 'Sammamish',
 'San Antonio',
 'San Bernardino',
 'San Bruno',
 'San Diego',
 'San Francisco',
 'San German',
 'San Geronimo',
 'San Jose',
 'San Juan',
 'San Leandro',
 'San Luis Obispo',
 'San Mateo',
 'San Pedro',
 'San Quentin',
 'San Rafael',
 'San Simeon',
 'Sandy',
 'Sandy Springs',
 'Santa Ana',
 'Santa Barbara',
 'Santa Clara',
 'Santa Cruz',
 'Santa Fe',
 'Santa Fe Springs',
 'Santa Isabel',
 'Santa Monica',
 'Santa Rosa',
 'Santurce',
 'Sausalito',
 'Savannah',
 'Schaumburg',
 'Schenectady',
 'Scotia',
 'Scott Lake',
 'Scottsdale',
 'Seabrook',
 'Seaside Park',
 'Seattle',
 'Seboruco',
 'Sedona',
 'Seven Corners',
 'Seward',
 'Shady Side',
 'Shakopee',
 'Shanksville',
 'Shelton',
 'Shoreline',
 'Silver Spring',
 'Sioux Falls',
 'Skokie',
 'Snohomish',
 'Somerville',
 'Sonoma',
 'South Daytona',
 'South Fulton',
 'South Sioux City',
 'Spanish Valley',
 'Sparta',
 'Spokane',
 'Spokane Valley',
 'Springdale',
 'Springfield',
 'St. Albans',
 'St. Charles',
 'St. Cloud',
 'St. George',
 'St. Louis',
 'St. Paul',
 'St. Petersburg',
 'Stateline',
 'Stephens City',
 'Sterling',
 'Stockton',
 'Storrs',
 'Strong',
 'Stuart',
 'Suitland',
 'Summit',
 'Sunland Park',
 'Sunnyvale',
 'Sunrise',
 'Sutter Creek',
 'Sylvania',
 'Sylvester',
 'Syracuse',
 'Tacoma',
 'Tallahassee',
 'Tamarac',
 'Tampa',
 'Tarrytown',
 'Taycheedah',
 'Tempe',
 'Temple Terrace',
 'Terre Haute',
 'Texarkana',
 'The Dalles',
 'Thonotosassa',
 'Thousand Oaks',
 'Three Forks',
 'Toa Baja',
 'Toledo',
 'Tomah',
 'Torrance',
 'Tracy',
 'Triangle',
 'Trona',
 'Tucson',
 'Tukwila',
 'Tulsa',
 'Tumwater',
 'Tupelo',
 'Tuscaloosa',
 'Tyngsborough',
 'Ukiah',
 'Union',
 'Union City',
 'University Heights',
 'Unknown',
 'Urbana',
 'Utica',
 'Vacaville',
 'Vail',
 'Vale',
 'Vallejo',
 'Valley Falls',
 'Vancouver',
 'Vega Baja',
 'Venice',
 'Ventura',
 'Vernon',
 'Victoria',
 'Vieques',
 'Villamar',
 'Viola',
 'Virginia Beach',
 'Viroqua',
 'Visalia',
 'Vivian',
 'Wakefield',
 'Walnut Creek',
 'Waltham',
 'Warren',
 'Warrensville Heights',
 'Warrenville',
 'Warwick',
 'Washington',
 'Washington county',
 'Watertown',
 'Watsonville',
 'Waukesha',
 'Wauwatosa',
 'Webster',
 'Weehawken',
 'Weirton',
 'Wellesley',
 'Wells',
 'Wenden',
 'West',
 'West Covina',
 'West Des Moines',
 'West Jordan',
 'West Lake Hills',
 'West Orange',
 'West Palm Beach',
 'West Point',
 'Westminster',
 'Westmont',
 'Weymouth',
 'Wheaton',
 'White Sulphur Springs',
 'Whitefish Bay',
 'Whitewater',
 'Wichita',
 'Wilkinsburg',
 'Williamsport',
 'Willow Street',
 'Wilmington',
 'Wimauma',
 'Winthrop',
 'Woodbridge',
 'Woodinville',
 'Woodside',
 'Worcester',
 'Wounded Knee',
 'Wrightsville',
 'Yakima',
 'Yamhill',
 'Yauco',
 'Yelm',
 'Youngstown',
 'Ypsilanti',
 'Yuba City']

In [142]:
mycities = ['New York','New York City','Washington','Chicago','Miami','Houston','Los Angeles','Seattle']

for x in mycities :
    if x in gtduscity:
        print(f"{x} is in the database.")
    else:
        print(f"{x} is not in the database.")

New York is in the database.
New York City is in the database.
Washington is in the database.
Chicago is in the database.
Miami is in the database.
Houston is in the database.
Los Angeles is in the database.
Seattle is in the database.

In [146]:
gtdmycities = gtdbig[gtdbig['city'].isin(mycities)]
print(gtdmycities.city.unique())
print(gtdmycities.info())

['New York City' 'Seattle' 'Chicago' 'Los Angeles' 'Washington' 'Houston'
 'Miami' 'New York']
<class 'pandas.core.frame.DataFrame'>
Index: 904 entries, 17 to 210889
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 960.5+ KB
None

In [147]:
gtdmycities.isna().sum()

eventid         0
iyear           0
imonth          0
iday            0
approxdate    899
             ...
INT_LOG         0
INT_IDEO        0
INT_MISC        0
INT_ANY         0
related       732
Length: 135, dtype: int64

In [148]:
allna = gtdmycities.isna().sum().sort_values(ascending = False)
allna

gsubname3           904
weapsubtype4_txt    904
weaptype4           904
weaptype4_txt       904
weapsubtype4        904
                   ...
crit2                 0
crit1                 0
property              0
vicinity              0
eventid               0
Length: 135, dtype: int64

In [149]:
na_dict = allna.to_dict()

In [150]:
na_dict

{'gsubname3': 904,
 'weapsubtype4_txt': 904,
 'weaptype4': 904,
 'weaptype4_txt': 904,
 'weapsubtype4': 904,
 'gname3': 903,
 'gsubname2': 903,
 'claim3': 903,
 'claimmode3': 903,
 'claimmode3_txt': 903,
 'attacktype3_txt': 903,
 'guncertain3': 903,
 'attacktype3': 903,
 'ransompaid': 901,
 'divert': 901,
 'ransompaidus': 901,
 'corp3': 900,
 'ransomamtus': 900,
 'ransomnote': 900,
 'target3': 899,
 'targsubtype3_txt': 899,
 'natlty3': 899,
 'targsubtype3': 899,
 'targtype3_txt': 899,
 'targtype3': 899,
 'approxdate': 899,
 'natlty3_txt': 899,
 'claimmode2': 898,
 'claimmode2_txt': 898,
 'resolution': 898,
 'kidhijcountry': 898,
 'ransomamt': 898,
 'claim2': 897,
 'guncertain2': 895,
 'gname2': 895,
 'weapsubtype3': 895,
 'weapsubtype3_txt': 895,
 'ndays': 894,
 'nreleased': 893,
 'gsubname': 893,
 'weaptype3': 893,
 'weaptype3_txt': 893,
 'nhours': 891,
 'attacktype2_txt': 890,
 'attacktype2': 890,
 'hostkidoutcome_txt': 888,
 'hostkidoutcome': 888,
 'compclaim': 888,
 'corp2': 883,
 'natlty2_txt': 881,
 'natlty2': 881,
 'targsubtype2': 880,
 'nhostkid': 880,
 'nhostkidus': 880,
 'targsubtype2_txt': 880,
 'target2': 880,
 'targtype2_txt': 874,
 'targtype2': 874,
 'weapsubtype2_txt': 870,
 'weapsubtype2': 870,
 'weaptype2': 855,
 'weaptype2_txt': 855,
 'alternative': 828,
 'alternative_txt': 828,
 'related': 732,
 'claimmode': 730,
 'claimmode_txt': 730,
 'propvalue': 676,
 'propcomment': 663,
 'scite3': 623,
 'addnotes': 622,
 'location': 567,
 'motive': 564,
 'scite2': 530,
 'summary': 480,
 'scite1': 480,
 'nperpcap': 477,
 'propextent': 477,
 'propextent_txt': 477,
 'claimed': 476,
 'nwoundte': 444,
 'nkillter': 444,
 'nwoundus': 432,
 'nperps': 428,
 'nkillus': 421,
 'corp1': 377,
 'ransom': 183,
 'weapdetail': 110,
 'weapsubtype1_txt': 99,
 'weapsubtype1': 99,
 'targsubtype1': 52,
 'targsubtype1_txt': 52,
 'ishostkid': 49,
 'nwound': 38,
 'nkill': 36,
 'target1': 16,
 'natlty1': 4,
 'natlty1_txt': 4,
 'provstate': 0,
 'imonth': 0,
 'region_txt': 0,
 'region': 0,
 'country_txt': 0,
 'country': 0,
 'extended': 0,
 'iday': 0,
 'latitude': 0,
 'dbsource': 0,
 'INT_LOG': 0,
 'INT_IDEO': 0,
 'INT_MISC': 0,
 'INT_ANY': 0,
 'city': 0,
 'guncertain1': 0,
 'longitude': 0,
 'attacktype1': 0,
 'iyear': 0,
 'individual': 0,
 'gname': 0,
 'weaptype1': 0,
 'weaptype1_txt': 0,
 'targtype1_txt': 0,
 'targtype1': 0,
 'attacktype1_txt': 0,
 'suicide': 0,
 'specificity': 0,
 'success': 0,
 'multiple': 0,
 'doubtterr': 0,
 'crit3': 0,
 'crit2': 0,
 'crit1': 0,
 'property': 0,
 'vicinity': 0,
 'eventid': 0}

In [151]:
len(na_dict)

135

In [160]:
na_keep = {k:v for k,v in na_dict.items() if v < 300}
len(na_keep)

49

In [153]:
na_del = {k:v for k,v in na_dict.items() if v > 300}

In [161]:
col_to_drop = [feature for feature in na_del.keys()]
col_to_drop

['gsubname3',
 'weapsubtype4_txt',
 'weaptype4',
 'weaptype4_txt',
 'weapsubtype4',
 'gname3',
 'gsubname2',
 'claim3',
 'claimmode3',
 'claimmode3_txt',
 'attacktype3_txt',
 'guncertain3',
 'attacktype3',
 'ransompaid',
 'divert',
 'ransompaidus',
 'corp3',
 'ransomamtus',
 'ransomnote',
 'target3',
 'targsubtype3_txt',
 'natlty3',
 'targsubtype3',
 'targtype3_txt',
 'targtype3',
 'approxdate',
 'natlty3_txt',
 'claimmode2',
 'claimmode2_txt',
 'resolution',
 'kidhijcountry',
 'ransomamt',
 'claim2',
 'guncertain2',
 'gname2',
 'weapsubtype3',
 'weapsubtype3_txt',
 'ndays',
 'nreleased',
 'gsubname',
 'weaptype3',
 'weaptype3_txt',
 'nhours',
 'attacktype2_txt',
 'attacktype2',
 'hostkidoutcome_txt',
 'hostkidoutcome',
 'compclaim',
 'corp2',
 'natlty2_txt',
 'natlty2',
 'targsubtype2',
 'nhostkid',
 'nhostkidus',
 'targsubtype2_txt',
 'target2',
 'targtype2_txt',
 'targtype2',
 'weapsubtype2_txt',
 'weapsubtype2',
 'weaptype2',
 'weaptype2_txt',
 'alternative',
 'alternative_txt',
 'related',
 'claimmode',
 'claimmode_txt',
 'propvalue',
 'propcomment',
 'scite3',
 'addnotes',
 'location',
 'motive',
 'scite2',
 'summary',
 'scite1',
 'nperpcap',
 'propextent',
 'propextent_txt',
 'claimed',
 'nwoundte',
 'nkillter',
 'nwoundus',
 'nperps',
 'nkillus',
 'corp1']

In [162]:
gtdtrim = gtdmycities.drop(columns = col_to_drop)

In [163]:
gtdtrim.info()

<class 'pandas.core.frame.DataFrame'>
Index: 904 entries, 17 to 210889
Data columns (total 49 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   eventid           904 non-null    int64
 1   iyear             904 non-null    int64
 2   imonth            904 non-null    int64
 3   iday              904 non-null    int64
 4   extended          904 non-null    int64
 5   country           904 non-null    int64
 6   country_txt       904 non-null    object
 7   region            904 non-null    int64
 8   region_txt        904 non-null    object
 9   provstate         904 non-null    object
 10  city              904 non-null    object
 11  latitude          904 non-null    float64
 12  longitude         904 non-null    float64
 13  specificity       904 non-null    float64
 14  vicinity          904 non-null    int64
 15  crit1             904 non-null    int64
 16  crit2             904 non-null    int64
 17  crit3             904 non-null    int64
 18  doubtterr         904 non-null    int64
 19  multiple          904 non-null    float64
 20  success           904 non-null    int64
 21  suicide           904 non-null    int64
 22  attacktype1       904 non-null    int64
 23  attacktype1_txt   904 non-null    object
 24  targtype1         904 non-null    int64
 25  targtype1_txt     904 non-null    object
 26  targsubtype1      852 non-null    float64
 27  targsubtype1_txt  852 non-null    object
 28  target1           888 non-null    object
 29  natlty1           900 non-null    float64
 30  natlty1_txt       900 non-null    object
 31  gname             904 non-null    object
 32  guncertain1       904 non-null    float64
 33  individual        904 non-null    int64
 34  weaptype1         904 non-null    int64
 35  weaptype1_txt     904 non-null    object
 36  weapsubtype1      805 non-null    float64
 37  weapsubtype1_txt  805 non-null    object
 38  weapdetail        794 non-null    object
 39  nkill             868 non-null    float64
 40  nwound            866 non-null    float64
 41  property          904 non-null    int64
 42  ishostkid         855 non-null    float64
 43  ransom            721 non-null    float64
 44  dbsource          904 non-null    object
 45  INT_LOG           904 non-null    int64
 46  INT_IDEO          904 non-null    int64
 47  INT_MISC          904 non-null    int64
 48  INT_ANY           904 non-null    int64
dtypes: float64(12), int64(23), object(14)
memory usage: 385.4+ KB

In [164]:
gtdtrim.isna().sum()

eventid               0
iyear                 0
imonth                0
iday                  0
extended              0
country               0
country_txt           0
region                0
region_txt            0
provstate             0
city                  0
latitude              0
longitude             0
specificity           0
vicinity              0
crit1                 0
crit2                 0
crit3                 0
doubtterr             0
multiple              0
success               0
suicide               0
attacktype1           0
attacktype1_txt       0
targtype1             0
targtype1_txt         0
targsubtype1         52
targsubtype1_txt     52
target1              16
natlty1               4
natlty1_txt           4
gname                 0
guncertain1           0
individual            0
weaptype1             0
weaptype1_txt         0
weapsubtype1         99
weapsubtype1_txt     99
weapdetail          110
nkill                36
nwound               38
property              0
ishostkid            49
ransom              183
dbsource              0
INT_LOG               0
INT_IDEO              0
INT_MISC              0
INT_ANY               0
dtype: int64

## Currently deciding which columns to keep - will need to look through GTD Codebook or just keep it at 50 col.